services:
    juiceshop:
        image: bkimminich/juice-shop
        ports:
            - 3000:3000
        restart: always
        networks:
            main:
                aliases:
                  - juiceshop
    nginx-juiceshop:
        depends_on:
            - juiceshop
        image: nginx-juiceshop
        ports:
            - 8080:80
        restart: always
        networks:
            main:
                aliases:
                  - nginx-juiceshop

networks:
  main:
